export class ProtocolloCemDto {
    aie?: string;
    dpia?: string;
    autore?: string;
    azione?: [];
    azionedup?: string;
    categoria?: string;
    cdsdata?: any;
    cdsora?: string;
    noteazione?:string;
    commriscontro?: string;
    congiunta?: string;
    data?: any;
    destinatario?: string;
    dirigente?: string;
    funzionario?: string;
    idprot?: number;
    mittente?: string;
    notadigos?: string;
    note?: string;
    numcodsito?: [];
    numprotcoll?: [];
    oggetto?: string;
    protocollo?: string;
    protcollegato?: string;
    protriferime?: [];
    riscontrogeos?: any;
    scadenza?: any;
    scadenza2?: any;
    senso?: string;
    simulazione?: any;
    sottocategoria?: string;
    statoimpianto?: string;
    statoprocedura?: any;
    subassegnazione?: [];
    tematica?: string;
    elencorumore?: [];
    elencoufficio?: [];
    numcodcar?: any;
    numcodprog?: any;

    numeroCodiceSitoPerSoprolluogo?: string;
    numeroCodiceSitoPerVincolata?: string;
    numeroCodiceSitoPerRichiesta?: string;
    codiceSitoPerRapportoDiMisura?: string;
    fatturazioneDaCompletare?: string;
}
